# Generated by Django 4.0.3 on 2022-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
